### ISSUE TITLE
Large Class: Embedded vectors

### ISSUE THREAD

**Issue by cloud9-xx** [liuhuigmail/DeepSmellDetection#4]
Are the embedded vectors (word2vec) the same as that of feature envy? If not, can download .npy files? as they are not uploaded.
thx, and sorry for the troubles.

**Comment by liuhuigmail** [comment]
@TyrantJin  please  response to the issue.  Thanks

**Comment by TyrantJin** [comment]
They are trained on the same corpus, and you can directly use.
